### ISSUE TITLE
Rename Auxfunction

### ISSUE THREAD

**Issue by elioscordo** [Dario1989a/pathToFullstack#2]
Auxfunction is too generic.
Use something like services.js for calls
and utils for util function   
https://github.com/Dario1989a/pathToFullstack/blob/43ae4aaaba9d14fce0a777c40701ddcc9716bc0a/client/src/components/auxFunction/auxFunctions.js#L2

**Comment by Dario1989a** [comment]
Implemented directly in functional component due to code readability
